# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Mitgliedsnummer')),
                ('firstname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('middlename', models.CharField(blank=True, max_length=500, null=True, verbose_name='weitere Vornamen')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('birthdate', models.DateField(verbose_name='Geburtsdatum')),
                ('address', models.CharField(max_length=500, verbose_name='Anschrift')),
                ('city', models.CharField(max_length=100, verbose_name='Ort')),
                ('zipcode', models.PositiveIntegerField(verbose_name='PLZ')),
                ('organisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gliederung')),
                ('haspaid', models.BooleanField(verbose_name='hat bezahlt?')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Offene Beiträge')),
                ('akk', models.BooleanField(verbose_name='ist akkreditiert?')),
            ],
        ),
    ]
